CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    AccountID NUMBER,
    TransactionType VARCHAR2(20),
    Amount NUMBER,
    LogDate DATE
);
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog
    (TransactionID, AccountID, TransactionType, Amount, LogDate)
    VALUES
    (:NEW.TransactionID,
     :NEW.AccountID,
     :NEW.TransactionType,
     :NEW.Amount,
     SYSDATE);
END;
/